apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-pod
  namespace: podinfo
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: break-after-delay
  namespace: broken-pod
spec:
  containers:
    - name: sleeper
      image: bash:5.2
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "Pod running... will fail in 30 seconds";
          sleep 30;
          echo "Simulated failure";
          exit 1
      readinessProbe:
        exec:
          command: ["bash", "-c", "test -f /tmp/healthy"]
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        exec:
          command: ["bash", "-c", "test -f /tmp/healthy"]
        initialDelaySeconds: 10
        periodSeconds: 5
